name: "Setup Dependencies"
description: "Setup tools/dependencies"
inputs:
  # Task
  install_task:
    description: "install task if true"
    default: "true"
  task_version:
    description: "version of task to install"
    default: "v3.44.0"

  service_path:
    description: "path to service within repo"
    default: ""

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.install_task == 'true' }}
      uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
      with:
        uri: "https://github.com/go-task/task/releases/download/${{ inputs.version }}/task_linux_amd64.tar.gz"
        name: task
        version: ${{ inputs.task_version }}

    - if: ${{ startsWith(inputs.service_path, 'go/') }}
      uses: actions/setup-go@v5.5.0
      with:
        go-version-file: ./${{ inputs.service_path }}/go.mod

    - if: ${{ startsWith(inputs.service_path, 'node/') || startsWith(inputs.service_path, 'react/') }}
      uses: actions/setup-node@v4
      with:
        node-version-file: ./${{ inputs.service_path }}/package.json

    - if: ${{startsWith(inputs.service_path, 'python/') }}
      uses: actions/setup-python@v5
      with:
        python-version-file: ./${{ inputs.service_path }}/pyproject.toml
