name: "Setup Dependencies"
description: "setup tools and dependencies"
inputs:
  install-task:
    description: install task if true
    default: "true"
  task-version:
    description: "version of task to install"
    default: "v3.44.1"


runs:
  using: composite
  steps:
    - name: Install task
      if: ${{ inputs.install-task == 'true' }}
      uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 #5.0.0
      with:
        uri: https://github.com/go-task/task/releases/download/${{ inputs.task-version }}/task_linux_amd64.tar.gz #v3.44.1
        name: task
        version: ${{ inputs.task-version }}