version: '3'

tasks:
  trigger-workflow:
    desc: Trigger GitHub Actions workflow_dispatch event using act
    cmds:
      - |
        act workflow_dispatch \
          --container-architecture linux/amd64 \
          -e {{.PWD}}/event.json \
          -P ubuntu-24.04=node:16-bullseye-slim \
          --directory ../../.. \
          -W .github/workflows/deploy.yaml