version: '3'

# NOTES:
#  - Because we use --no-skip-checkout + workflow_dispatch, you must commit your changes 
#    (it can be to a branch) in order for the checkout to work
tasks:
  trigger-workflow:
    desc: Trigger GitHub Actions workflow_dispatch event using act
    cmds:
      - |
        act workflow_dispatch \
          --container-architecture linux/amd64 \
          -e {{.PWD}}/event.json \
          -P ubuntu-24.04=catthehacker/ubuntu:act-22.04 \
          --directory ../../.. \
          --no-skip-checkout \
          -W .github/workflows/deploy.yaml