apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefixes-golang
  namespace: demo-app
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /api/golang
