version: '3'

env:
  GITHUB_TOKEN:
    sh: gh auth token

tasks:
  trigger-workflow:
    # Expects HONEYCOMB_OTLP_HEADERS to be defined in .secrets file
    desc: Trigger GitHub Actions workflow_run event using act
    cmds:
      - |
        act workflow_run \
          --container-architecture linux/amd64 \
          -s GITHUB_TOKEN="{{.GITHUB_TOKEN}}" \
          -e {{.PWD}}/event.json \
          -P ubuntu-24.04=node:16-bullseye-slim \
          --directory ../../.. \
          -W .github/workflows/export-timing-data.yaml