# This is used by the action https://github.com/dorny/paths-filter

# This is effectively serving as a naive target determinator (see: https://blog.swgillespie.me/posts/monorepo-ingredients/)

# ---- services ---------------------------------------------------------------
services/go/api-golang:
  - "services/go/api-golang/**"

services/node/api-node:
  - "services/node/api-node/**"

services/other/postgresql:
  - "services/other/postgresql/**"

services/python/load-generator-python:
  - "services/python/load-generator-python/**"

services/react/client-react:
  - "services/react/client-react/**"
