name: Build and Push Container Images

on:
  # NOTE: Disabling for now while iterating on other workflows...
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Paths Changes Filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  build-push-container-images:
    runs-on: ubuntu-24.04
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    needs: filter
    strategy:
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-dependencies
        with:
          install_task: "true"

      # TODO: generate tags
      # TODO: add docker build-push action
