name: Build and Push Container Images

on:
  # NOTE: Disabling for now while iterating on other workflows...
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    # TODO: enabled triggering build for specific service manually

permissions:
  actions: write # used to trigger deploy workflow
  contents: read

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Paths Changes Filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  build-push-container-images:
    runs-on: ubuntu-24.04
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    needs: filter
    strategy:
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-dependencies
        with:
          install_task: "true" # I will likely use task to generate the container repo name + tags
      # TODO: Add dockerhub secret and enable this step
      # - name: Login to Docker Hub
      #   uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # TODO: Replace with namespace setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Build and push Docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.service }}
          # TODO: generate real tags and push
          push: false
          tags: foobarbaz
          # TODO setup caching
          platforms: linux/amd64

      # Trigger deploy as a separate workflow to:
      #   1. enable running it manually via workflow_dispatch
      #   2. keep workflows smaller and more focused
      - name: Trigger Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run deploy.yaml \
            -f service=${{ matrix.service }} \
            -f version="TODO: REPLACE ME" \
            -f environment="prod" \
            -r ${GITHUB_REF}
