name: Close Stale Issues and PRs
on:
  # NOTE: Disabling for now while iterating on other workflows...
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
