name: Deploy Service to Environment

on:
  # This could use a workflow_call instead... (or have both)
  workflow_dispatch:
    inputs:
      service:
        description: "Path to the service to deploy (go/api-golang)"
        required: true
        type: string
      version:
        description: "Version to deploy"
        required: true
        type: string
      image_tag:
        description: "Image tag of the version to deploy"
        required: true
        type: string
      environment:
        description: "Target environment to deploy to"
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  update-manifests:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo ${{ inputs.service }}
          echo ${{ inputs.version }}
          echo ${{ inputs.image_tag }}
          echo ${{ inputs.environment }}
