name: Install Task

on:
  push:
    branches:
      - sp/tool-cache-experiments
  workflow_dispatch:

jobs:
  install-task-composite:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-task.yaml
        with:
          version: "v3.44.0"
      - run: |
          which task
          task --version
