name: Install Java

on:
  push:
    branches:
      - sp/tool-cache-experiments
    paths:
      - .github/workflows/install-java.yaml
  workflow_dispatch:

#

jobs:
  official-setup-java-21:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21" # Will use version preinstalled in runner image tool cache https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
      - run: |
          which java
          java -version

  # If you need a different version, it will either download every time from upstream
  official-setup-java-21-0-6:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21.0.6"
      - run: |
          which java
          java -version

  # ...or you can cache/restore after the first run
  official-setup-java-21-0-6-cache:
    runs-on: ubuntu-24.04
    env:
      JDK_DIR: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7.0.LTS
    steps:
      - name: Restore Java from cache
        id: cache-task
        uses: actions/cache@v4
        with:
          path: ${{ env.JDK_DIR }}
          key: jdk-21.0.6-${{ runner.os }}-${{ runner.arch }}
      - name: Add to path
        run: echo "${{ env.JDK_DIR }}/x64/bin" >> "$GITHUB_PATH"
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21.0.6"
      - run: |
          which java
          java -version

  # ...with the default GHA cache, this isnt any faster than downloading from upstream
  # but if we use namespace cache volumes...
  official-setup-java-21-0-6-namespace-cache:
    runs-on: namespace-profile-custom-image
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21.0.6"
      - run: |
          which java
          java -version

  # could also use a container image...

  # or a custom namespace runner image
