name: Run Tests

on:
  push:
    branches:
      - sp/tool-cache-experiments
  workflow_dispatch:

jobs:
  services-changed:
    runs-on: ubuntu-24.04
    outputs:
      go_services: ${{ steps.services-changed.outputs.go_services }}
      node_services: ${{ steps.services-changed.outputs.node_services }}
      python_services: ${{ steps.services-changed.outputs.python_services }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/services-changed
        id: services-changed
        with:
          github-token: $${{ github.token }}

  go-tests:
    runs-on: ubuntu-24.04
    if: ${{ needs.services-changed.outputs.go_services != '[]' && needs.services-changed.outputs.go_services != '' }}
    needs: services-changed
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.go_services) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-task
        with:
          version: "v3.44.0"
      - uses: actions/setup-go@v5.5.0
        with:
          go-version-file: ./${{ matrix.service }}/go.mod

  node-tests:
    runs-on: ubuntu-24.04
    if: ${{ needs.services-changed.outputs.node_services != '[]' && needs.services-changed.outputs.node_services != '' }}
    needs: services-changed
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.node_services) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-task
        with:
          version: "v3.44.0"
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./${{ matrix.service }}/package.json

  python-tests:
    runs-on: ubuntu-24.04
    if: ${{ needs.services-changed.outputs.python_services != '[]' && needs.services-changed.outputs.python_services != '' }}
    needs: services-changed
    strategy:
      matrix:
        service: ${{ fromJson(needs.services-changed.outputs.python_services) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-task
        with:
          version: "v3.44.0"
      - uses: actions/setup-python@v5
        with:
          python-version-file: ./${{ matrix.service }}/pyproject.toml
