name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - services/**
      - .github/workflows/test.yaml
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: filter
        id: filter
        uses: dorny/paths-filter@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  test:
    needs: filter
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js environment
        if: ${{ startsWith(matrix.service, 'services/node/') || startsWith(matrix.service, 'services/react/')}}
        uses: actions/setup-node@v7.0.0
        with: 
          node-version-file: ${{ matrix.service }}/package.json
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json
      
      - name: Setup Go environment
        if: ${{ startsWith(matrix.service, 'services/go/')}}
        uses: actions/setup-go@v7
        with: 
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Set up poetry
        if: ${{ startsWith(matrix.service, 'services/python/')}}
        uses: abatilo/actions-poetry@v4.0.0   

      - name: Setup Python environment
        if: ${{ startsWith(matrix.service, 'services/python/')}}
        uses: actions/setup-python@v7
        with: 
          python-version-file: ${{ matrix.service }}/pyproject.toml
          cache: poetry
          cache-dependency-path: ${{ matrix.service }}/poetry.lock

      - name: Install task
        uses: supplypike/setup-bin@v5
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.52.0/task_linux_amd64.tar.gz"
          name: task
          version: v3.52.0

      - name: Install node deps
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci

      - name: Run test
        working-directory: ${{ matrix.service }}
        run: |
          task test
